version: "3.2"
services:
  php:
    build: 
      context: .
    image: sisinder/6130-pro:8
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DB=studentdetails
    volumes:
      - ./files/:/var/main/html/
    ports:
      - "3000:80"
    container_name: sitefinal
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass 
      - MYSQL_DATABASE=studentdetails
    container_name: mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "4000:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: phpmyadmin
networks:
  frontend:
  backend:
    