FROM php:7.3-apache 
RUN docker-php-ext-install mysqli pdo_mysql
RUN apt-get update \
    && apt-get install -y libzip-dev \
    && apt-get install -y zlib1g-dev \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-install zip

RUN mkdir /project \
 && mkdir /project/studentdet \
 && mkdir /project/studentdet/files 


COPY files/ /project/studentdet/files/

RUN cp -r /project/studentdet/files/* /var/www/html/